# Rubrik RSC Configuration
# Please populate the values below.
RSC_DOMAIN: rubrik-gaia.my.rubrik.com
CLIENT_ID: client|019cd375-9e29-7527-84ca-b834f499263b
CLIENT_SECRET: x5-bDWv8jAkHy_QmnT7j2j4e7mOvwm2Nir77GRuG8m-qJKE_QeYwvl54oznbnB3f
